// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: types_v1.proto

package crud_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         string                 `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         string                 `protobuf:"bytes,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kind) Reset() {
	*x = Kind{}
	mi := &file_types_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kind) ProtoMessage() {}

func (x *Kind) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kind.ProtoReflect.Descriptor instead.
func (*Kind) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Kind) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *Kind) GetMinor() string {
	if x != nil {
		return x.Minor
	}
	return ""
}

type TimeBasedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // Storing any type of value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeBasedValue) Reset() {
	*x = TimeBasedValue{}
	mi := &file_types_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBasedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBasedValue) ProtoMessage() {}

func (x *TimeBasedValue) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBasedValue.ProtoReflect.Descriptor instead.
func (*TimeBasedValue) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{1}
}

func (x *TimeBasedValue) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeBasedValue) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TimeBasedValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type Relationship struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RelatedEntityId string                 `protobuf:"bytes,1,opt,name=relatedEntityId,proto3" json:"relatedEntityId,omitempty"`
	StartTime       string                 `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime         string                 `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Id              string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_types_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Relationship) GetRelatedEntityId() string {
	if x != nil {
		return x.RelatedEntityId
	}
	return ""
}

func (x *Relationship) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Relationship) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Relationship) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Relationship) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Entity struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Id            string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                 // Read-only unique identifier
	Kind          *Kind                          `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`             // Read-only entity type
	Created       string                         `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`       // Read-only created timestamp
	Terminated    string                         `protobuf:"bytes,4,opt,name=terminated,proto3" json:"terminated,omitempty"` // Nullable terminated timestamp
	Name          *TimeBasedValue                `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]*anypb.Any          `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`           // Metadata as a flexible key-value map
	Attributes    map[string]*TimeBasedValueList `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // Attributes as a time-based list
	Relationships map[string]*Relationship       `protobuf:"bytes,8,rep,name=relationships,proto3" json:"relationships,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Relationships to other entities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_types_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{3}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetKind() *Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Entity) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *Entity) GetTerminated() string {
	if x != nil {
		return x.Terminated
	}
	return ""
}

func (x *Entity) GetName() *TimeBasedValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Entity) GetMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entity) GetAttributes() map[string]*TimeBasedValueList {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entity) GetRelationships() map[string]*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

// Wrapper for a repeated TimeBasedValue (since Protobuf does not support nested lists in maps)
type TimeBasedValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*TimeBasedValue      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeBasedValueList) Reset() {
	*x = TimeBasedValueList{}
	mi := &file_types_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBasedValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBasedValueList) ProtoMessage() {}

func (x *TimeBasedValueList) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBasedValueList.ProtoReflect.Descriptor instead.
func (*TimeBasedValueList) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{4}
}

func (x *TimeBasedValueList) GetValues() []*TimeBasedValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// Request message for reading an entity
type ReadEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Entity        *Entity                `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Output        []string               `protobuf:"bytes,3,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadEntityRequest) Reset() {
	*x = ReadEntityRequest{}
	mi := &file_types_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEntityRequest) ProtoMessage() {}

func (x *ReadEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEntityRequest.ProtoReflect.Descriptor instead.
func (*ReadEntityRequest) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ReadEntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadEntityRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *ReadEntityRequest) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

// Request message for deleting an entity by ID
type EntityId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityId) Reset() {
	*x = EntityId{}
	mi := &file_types_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityId) ProtoMessage() {}

func (x *EntityId) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityId.ProtoReflect.Descriptor instead.
func (*EntityId) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{6}
}

func (x *EntityId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for updating an entity
type UpdateEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Entity        *Entity                `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityRequest) Reset() {
	*x = UpdateEntityRequest{}
	mi := &file_types_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityRequest) ProtoMessage() {}

func (x *UpdateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntityRequest) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEntityRequest) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// Empty message response
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_types_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{8}
}

// EntityList represents a list of entities
type EntityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityList) Reset() {
	*x = EntityList{}
	mi := &file_types_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityList) ProtoMessage() {}

func (x *EntityList) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityList.ProtoReflect.Descriptor instead.
func (*EntityList) Descriptor() ([]byte, []int) {
	return file_types_v1_proto_rawDescGZIP(), []int{9}
}

func (x *EntityList) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_types_v1_proto protoreflect.FileDescriptor

const file_types_v1_proto_rawDesc = "" +
	"\n" +
	"\x0etypes_v1.proto\x12\x04crud\x1a\x19google/protobuf/any.proto\"2\n" +
	"\x04Kind\x12\x14\n" +
	"\x05major\x18\x01 \x01(\tR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\tR\x05minor\"t\n" +
	"\x0eTimeBasedValue\x12\x1c\n" +
	"\tstartTime\x18\x01 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x02 \x01(\tR\aendTime\x12*\n" +
	"\x05value\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\x94\x01\n" +
	"\fRelationship\x12(\n" +
	"\x0frelatedEntityId\x18\x01 \x01(\tR\x0frelatedEntityId\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\tR\aendTime\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xdb\x04\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\x04kind\x18\x02 \x01(\v2\n" +
	".crud.KindR\x04kind\x12\x18\n" +
	"\acreated\x18\x03 \x01(\tR\acreated\x12\x1e\n" +
	"\n" +
	"terminated\x18\x04 \x01(\tR\n" +
	"terminated\x12(\n" +
	"\x04name\x18\x05 \x01(\v2\x14.crud.TimeBasedValueR\x04name\x126\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1a.crud.Entity.MetadataEntryR\bmetadata\x12<\n" +
	"\n" +
	"attributes\x18\a \x03(\v2\x1c.crud.Entity.AttributesEntryR\n" +
	"attributes\x12E\n" +
	"\rrelationships\x18\b \x03(\v2\x1f.crud.Entity.RelationshipsEntryR\rrelationships\x1aQ\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\x1aW\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.crud.TimeBasedValueListR\x05value:\x028\x01\x1aT\n" +
	"\x12RelationshipsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.crud.RelationshipR\x05value:\x028\x01\"B\n" +
	"\x12TimeBasedValueList\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.crud.TimeBasedValueR\x06values\"a\n" +
	"\x11ReadEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x06entity\x18\x02 \x01(\v2\f.crud.EntityR\x06entity\x12\x16\n" +
	"\x06output\x18\x03 \x03(\tR\x06output\"\x1a\n" +
	"\bEntityId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x13UpdateEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x06entity\x18\x02 \x01(\v2\f.crud.EntityR\x06entity\"\a\n" +
	"\x05Empty\"6\n" +
	"\n" +
	"EntityList\x12(\n" +
	"\bentities\x18\x01 \x03(\v2\f.crud.EntityR\bentities2\x8f\x02\n" +
	"\vCrudService\x12*\n" +
	"\fCreateEntity\x12\f.crud.Entity\x1a\f.crud.Entity\x123\n" +
	"\n" +
	"ReadEntity\x12\x17.crud.ReadEntityRequest\x1a\f.crud.Entity\x129\n" +
	"\fReadEntities\x12\x17.crud.ReadEntityRequest\x1a\x10.crud.EntityList\x127\n" +
	"\fUpdateEntity\x12\x19.crud.UpdateEntityRequest\x1a\f.crud.Entity\x12+\n" +
	"\fDeleteEntity\x12\x0e.crud.EntityId\x1a\v.crud.EmptyB\x1cZ\x1alk/datafoundation/crud-apib\x06proto3"

var (
	file_types_v1_proto_rawDescOnce sync.Once
	file_types_v1_proto_rawDescData []byte
)

func file_types_v1_proto_rawDescGZIP() []byte {
	file_types_v1_proto_rawDescOnce.Do(func() {
		file_types_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_v1_proto_rawDesc), len(file_types_v1_proto_rawDesc)))
	})
	return file_types_v1_proto_rawDescData
}

var file_types_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_types_v1_proto_goTypes = []any{
	(*Kind)(nil),                // 0: crud.Kind
	(*TimeBasedValue)(nil),      // 1: crud.TimeBasedValue
	(*Relationship)(nil),        // 2: crud.Relationship
	(*Entity)(nil),              // 3: crud.Entity
	(*TimeBasedValueList)(nil),  // 4: crud.TimeBasedValueList
	(*ReadEntityRequest)(nil),   // 5: crud.ReadEntityRequest
	(*EntityId)(nil),            // 6: crud.EntityId
	(*UpdateEntityRequest)(nil), // 7: crud.UpdateEntityRequest
	(*Empty)(nil),               // 8: crud.Empty
	(*EntityList)(nil),          // 9: crud.EntityList
	nil,                         // 10: crud.Entity.MetadataEntry
	nil,                         // 11: crud.Entity.AttributesEntry
	nil,                         // 12: crud.Entity.RelationshipsEntry
	(*anypb.Any)(nil),           // 13: google.protobuf.Any
}
var file_types_v1_proto_depIdxs = []int32{
	13, // 0: crud.TimeBasedValue.value:type_name -> google.protobuf.Any
	0,  // 1: crud.Entity.kind:type_name -> crud.Kind
	1,  // 2: crud.Entity.name:type_name -> crud.TimeBasedValue
	10, // 3: crud.Entity.metadata:type_name -> crud.Entity.MetadataEntry
	11, // 4: crud.Entity.attributes:type_name -> crud.Entity.AttributesEntry
	12, // 5: crud.Entity.relationships:type_name -> crud.Entity.RelationshipsEntry
	1,  // 6: crud.TimeBasedValueList.values:type_name -> crud.TimeBasedValue
	3,  // 7: crud.ReadEntityRequest.entity:type_name -> crud.Entity
	3,  // 8: crud.UpdateEntityRequest.entity:type_name -> crud.Entity
	3,  // 9: crud.EntityList.entities:type_name -> crud.Entity
	13, // 10: crud.Entity.MetadataEntry.value:type_name -> google.protobuf.Any
	4,  // 11: crud.Entity.AttributesEntry.value:type_name -> crud.TimeBasedValueList
	2,  // 12: crud.Entity.RelationshipsEntry.value:type_name -> crud.Relationship
	3,  // 13: crud.CrudService.CreateEntity:input_type -> crud.Entity
	5,  // 14: crud.CrudService.ReadEntity:input_type -> crud.ReadEntityRequest
	5,  // 15: crud.CrudService.ReadEntities:input_type -> crud.ReadEntityRequest
	7,  // 16: crud.CrudService.UpdateEntity:input_type -> crud.UpdateEntityRequest
	6,  // 17: crud.CrudService.DeleteEntity:input_type -> crud.EntityId
	3,  // 18: crud.CrudService.CreateEntity:output_type -> crud.Entity
	3,  // 19: crud.CrudService.ReadEntity:output_type -> crud.Entity
	9,  // 20: crud.CrudService.ReadEntities:output_type -> crud.EntityList
	3,  // 21: crud.CrudService.UpdateEntity:output_type -> crud.Entity
	8,  // 22: crud.CrudService.DeleteEntity:output_type -> crud.Empty
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_types_v1_proto_init() }
func file_types_v1_proto_init() {
	if File_types_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_v1_proto_rawDesc), len(file_types_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_types_v1_proto_goTypes,
		DependencyIndexes: file_types_v1_proto_depIdxs,
		MessageInfos:      file_types_v1_proto_msgTypes,
	}.Build()
	File_types_v1_proto = out.File
	file_types_v1_proto_goTypes = nil
	file_types_v1_proto_depIdxs = nil
}
